
-- Write SQL queries to perform the following tasks using the Sakila database:

-- 1. List the number of films per category.
-- 2. Retrieve the store ID, city, and country for each store.
-- 3. Calculate the total revenue generated by each store in dollars.
-- 4. Determine the average running time of films for each category.

-- 1.

use sakila;

SELECT * FROM FILM;

SELECT 
    c.name AS category, COUNT(f.title) AS number_of_movies
FROM
    category c
        JOIN
    film_category fm ON c.category_id = fm.category_id
		JOIN
	film f ON f.film_id = fm.film_id
GROUP BY
	category;

-- 2.

SELECT 
    s.store_id, c.city, co.country
FROM
    store s
		JOIN
	address ad ON s.address_id = ad.address_id
		JOIN
	city c ON ad.city_id = c.city_id
		JOIN
	country co ON co.country_id = c.country_id;

-- 3.

SELECT 
    staff_id AS store, SUM(amount) AS revenue
FROM
    payment
GROUP BY staff_id;

-- 4. Determine the average running time of films for each category.

SELECT 
    c.name AS category, AVG(f.length)
FROM
    category c
        JOIN
    film_category fm ON c.category_id = fm.category_id
		JOIN
	film f ON fm.film_id = f.film_id
GROUP BY category;


